import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DialogProvider } from "@/context/dialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import GlobalWindowFrame from "@/components/GlobalWindowFrame";

import { SettingsProvider } from "@/context/SettingsContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-neutral-950 text-white`}
      >
        <SettingsProvider>
          <DialogProvider>
            <GlobalWindowFrame>
              {children}
            </GlobalWindowFrame>
          </DialogProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
