import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";
import { DialogProvider } from "@/hooks/dialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  adjustFontFallback: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  adjustFontFallback: false,
});

const prompt = Prompt({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["thai"],
  variable: "--font-prompt",
  display: 'swap',
});

export const metadata = {
  title: "Ducksy",
  description: "Generated by create next app",
};

import GlobalWindowFrame from "@/components/GlobalWindowFrame";

import { SettingsProvider } from "@/hooks/SettingsContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${prompt.variable} font-sans antialiased bg-neutral-950 text-white`}
      >
        <SettingsProvider>
          <DialogProvider>
            <GlobalWindowFrame>
              {children}
            </GlobalWindowFrame>
          </DialogProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
